### ISSUE TITLE
example for jupyter + nglview (+ pandas?)

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/scipy_proceedings#18]
@dotsdl (or someone else) can you provide a representative snapshot of a Jupyter notebook session that shows how one can "typically" work with MDAnalysis interactively? It would be nice to have something like 
- load trajectory
- visualize with nglview
- compute something (maybe using pandas)
- plot with matplotlib (or pandas/seaborn)

I'd like to have
- [ ] image of the notebook in the browser
- [ ] python code that could be shown in the paper

**Comment by kain88-de** [comment]
http://www.mdanalysis.org/2016/03/14/nglview/

we could start from this and additionally compute the RMSD

**Comment by kain88-de** [comment]
We can publish the notebook as a gist and link to it in the paper

**Comment by kain88-de** [comment]
![notebook-example](https://cloud.githubusercontent.com/assets/4302678/15633697/5f387504-25b4-11e6-857f-ea7338bb780d.png)

[gist](https://gist.github.com/kain88-de/8b1de3453512001ce6ff1d48ec6aa052)

I'm not sure how you want to include them exactly though but feel free to use them.

I'm not sure about the screenshot because it will be to small to recognize anything. Code example are fine though.

**Comment by dotsdl** [comment]
I can work on making this a working section in the paper. Fine with you, @kain88-de?

**Comment by kain88-de** [comment]
yeah sure. It is only a copy of your blog post anyway.

**Comment by dotsdl** [comment]
Cool. Working on it now.
