### ISSUE TITLE
internal links missing

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/scipy_proceedings#39]
Links to sections do NOT work with labels/ref — need to find a way to do this or remove internal links altogether.

**Comment by ianmkenney** [comment]
The problem is that the generated LaTeX document has `\setcounter{secnumdepth}{0}` and this seems to make it so the references are not valid. I can force references to work by changing 0 to 4 since the deepest sections we have are technically LaTeX paragraphs. I don't think there is a way for us to get around this.

**Comment by orbeckst** [comment]
SciPy might not like us messing up their formatting.

Can we use [\nameref](https://en.wikibooks.org/wiki/LaTeX/Labels_and_Cross-referencing#nameref) ?

**Comment by ianmkenney** [comment]
This is a rather involved process. In order to use `\nameref`, you need to define a new new docutils role that takes the `inputsection` from :nameref:\`inputsection\`. I've added this feature, but if the names of the sections are long it's pretty cluttered. 

As a workaround I defined another role "textref" that can create a hyperref to any valid latex label (which is another problem, see the metadata listing attempts at a label). Given that you have a valid label you can then use:

:textref:\`my-valid-label|arbitrary text for the link text\`

@orbeckst do with this as you'd like!

**Comment by orbeckst** [comment]
@ianmkenney did this break the normal
```reST
.. figure:: figures/MDAKitFramework.png

   Workflow diagram of the MDAKit framework.
   Starting from the creation of an MDAKit package, with the help of documentation and the MDAKit cookiecutter, the package then goes through the process of being added to the MDAKit registry, undergoing continuous validation and review and eventually reaching the stage of publication.
   :label:`fig:workflow`


The MDAKit framework (Fig. :ref:`fig:workflow`) is designed to be a complete workflow to help and incentivize developers to go from the initial stages of package development all the way through to the long term maintenance of a mature codebase, while adhering to best practices.
```

When you look at the PDF we get as caption
```
Fig. 1: Workflow diagram of the MDAKit framework. Starting from the creation of an MDAKit package, with the help of documentation and the MDAKit cookiecutter, the package then goes through the process of being added to the MDAKit registry, undergoing continuous vali- dation and review and eventually reaching the stage of publication. fig:workflow
```
where the `:label:` is not turned into a label but instead is printed. Consequently, in text, the ref is not resolved
```
The MDAKit framework (Fig. fig:workflow) is designed to be a complete workflow t
```

Can you please fix this somehow?

**Comment by orbeckst** [comment]
The links appear to be generated in the scipy build system, just not locally when I build it.
